[package]
name = "kip-plugin"
version = "0.1.0"
edition = "2021"

[dependencies]
kip-storage.workspace = true
serde_json.workspace = true
serde.workspace = true
tokio.workspace = true
thiserror.workspace = true
tracing.workspace = true
