[package]
name = "homed-gh"
version = "0.1.0"
edition = "2021"

[dependencies]
homed-storage.workspace = true
octocrab.workspace = true
dotenv.workspace = true

[dev-dependencies]
tokio.workspace = true
